export const AUTH = 'AUTH'
export const LOGOUT = 'LOGOUT'
export const CHECKRESET = 'CHECKRESET'
export const CHECKPASSWORD = 'CHECKPASSWORD'

export const UPDATE_TEACHER_CREDS = 'UPDATE_TEACHER_CREDS'

export const CREATE_TEACHER = 'CREATE_TEACHER '
export const FETCH_ALL_TEACHERS = 'FETCH_ALL_TEACHERS'
export const DELETE_TEACHER = 'DELETE_TEACHER'
export const UPDATE_TEACHER = 'UPDATE_TEACHER'

export const CREATE_ADMIN = 'CREATE_ADMIN'
export const FETCH_ALL_ADMIN = 'FETCH_ALL_ADMINS'
export const DELETE_ADMIN  = 'DELETE_ADMIN'
export const UPDATE_ADMIN  = 'UPDATE_ADMIN'

export const CREATE_STUDENT = 'CREATE_STUDENT'

export const FETCH_ALL_STUDENT = 'FETCH_ALL_STUDENTS'
export const FETCH_ALL_STUDENT_BY_TEACHER = 'FETCH_ALL_STUDENT_BY_TEACHER'
export const DELETE_STUDENT  = 'DELETE_STUDENT'
export const UPDATE_STUDENT  = 'UPDATE_STUDENT'

export const CREATE_CLASS = 'CREATE_CLASS'
export const FETCH_ALL_CLASS = 'FETCH_ALL_CLASS'
export const FETCH_ALL_CLASS_BY_SEARCH = 'FETCH_ALL_CLASS_BY_SEARCH'
export const DELETE_CLASS  = 'DELETE_CLASS'
export const UPDATE_CLASS = 'UPDATE_CLASS'

export const ISCLICKED = 'ISCLICKED'
export const ACTIVEMENU = 'ACTIVEMENU'
export const SCREENSIZE = 'SCREENSIZE'
export const SETCOLOR = 'SETCOLOR'
export const SETTHEMESETTINGS = 'SETTHEMESETTINGS'
export const SETMODE = 'SETMODE'

export const FETCH_ALL_SESSIONS = 'FETCH_ALL_SESSIONS'
export const FETCH_SESSIONS_BY_PAGE = 'FETCH_SESSIONS_BY_PAGE'
export const FETCH_SESSIONS_FOR_CALENDAR = 'FETCH_SESSIONS_FOR_CALENDAR'
export const CREATE_SESSION = 'CREATE_SESSION'
export const DELETE_SESSION  = 'DELETE_SESSION'
export const UPDATE_SESSION  = 'UPDATE_SESSION'

export const CREATE_GRADE = 'CREATE_GRADE'
export const FETCH_GRADES_BY_STUDENT = 'FETCH_GRADES_BY_STUDENT'
export const FETCH_ALL_GRADES = 'FETCH_ALL_GRADES'
export const DELETE_GRADES  = 'DELETE_GRADES'
export const UPDATE_GRADES = 'UPDATE_GRADES'

export const CREATE_HOMEWORK = 'CREATE_HOMEWORK'
export const FETCH_HOMEWORK_BY_STUDENT = 'FETCH_HOMEWORK_BY_STUDENT'
export const FETCH_ALL_HOMEWORK = 'FETCH_ALL_HOMEWORK'
export const DELETE_HOMEWORK  = 'DELETE_HOMEWORK'
export const UPDATE_HOMEWORK = 'UPDATE_HOMEWORK'


export const FETCHCLASSES_BY_SEARCH = 'FETCHCLASSES_BY_SEARCH'
export const FETCHSESSIONS_BY_SEARCH = 'FETCHSESSIONS_BY_SEARCH'

export const FETCH_PAYROLL_BY_SEARCH = 'FETCH_PAYROLL_BY_SEARCH'

export const FETCH_FINANCIALS_BY_DATA = 'FETCH_FINANCIALS_BY_DATA'
export const FETCH_ADMIN_TODAY_OVERVIEW = 'FETCH_ADMIN_TODAY_OVERVIEW'
export const FETCH_TEACHER_TODAY_OVERVIEW = 'FETCH_TEACHER_TODAY_OVERVIEW'